management.endpoints.web.exposure.include: '*'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: dbuser
    password: dbpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect