management:
  endpoints:
    web.exposure.include: '*'
    health.sensitive: false
  health:
    db.enabled: true
    defaults.enabled: true
  endpoint:
    health.show-details: always

spring:
  kafka:
    bootstrap-servers:
      - localhost:9094
    security.protocol: PLAINTEXT
    producer:
#      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/contacts?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect