server.port: 8082
application:
  database.name: 'service_b'
spring:
  datasource:
    url: jdbc:h2:mem:${application.database.name}
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect