out.topic: test
serviceb.base.url: http://localhost:8081

management:
  endpoints:
    web.exposure.include: '*'
    health.sensitive: false
  health:
    db.enabled: true
    defaults.enabled: true
  endpoint:
    health.show-details: always

spring:
#  cloud.stream:
#    function.definition: process
#    bindings:
#      output-out-0:
#        destination: test
#        group: group1
#    kafka:
#      bindings:
#        output-out-0:
#          producer:
#            configuration:
#              value.serializer: org.apache.kafka.common.serialization.StringSerializer
  kafka:
    bootstrap-servers:
      - localhost:9094
    security.protocol: PLAINTEXT
    producer:
#      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/contacts?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect